// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cosmos/ibc-go/v8/modules/core/05-port/types (interfaces: IBCModule)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=./test/mock/ibc_module.go github.com/cosmos/ibc-go/v8/modules/core/05-port/types IBCModule
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	types "github.com/cosmos/cosmos-sdk/types"
	types0 "github.com/cosmos/ibc-go/modules/capability/types"
	types1 "github.com/cosmos/ibc-go/v8/modules/core/04-channel/types"
	exported "github.com/cosmos/ibc-go/v8/modules/core/exported"
	gomock "go.uber.org/mock/gomock"
)

// MockIBCModule is a mock of IBCModule interface.
type MockIBCModule struct {
	ctrl     *gomock.Controller
	recorder *MockIBCModuleMockRecorder
	isgomock struct{}
}

// MockIBCModuleMockRecorder is the mock recorder for MockIBCModule.
type MockIBCModuleMockRecorder struct {
	mock *MockIBCModule
}

// NewMockIBCModule creates a new mock instance.
func NewMockIBCModule(ctrl *gomock.Controller) *MockIBCModule {
	mock := &MockIBCModule{ctrl: ctrl}
	mock.recorder = &MockIBCModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBCModule) EXPECT() *MockIBCModuleMockRecorder {
	return m.recorder
}

// OnAcknowledgementPacket mocks base method.
func (m *MockIBCModule) OnAcknowledgementPacket(ctx types.Context, packet types1.Packet, acknowledgement []byte, relayer types.AccAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnAcknowledgementPacket", ctx, packet, acknowledgement, relayer)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnAcknowledgementPacket indicates an expected call of OnAcknowledgementPacket.
func (mr *MockIBCModuleMockRecorder) OnAcknowledgementPacket(ctx, packet, acknowledgement, relayer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAcknowledgementPacket", reflect.TypeOf((*MockIBCModule)(nil).OnAcknowledgementPacket), ctx, packet, acknowledgement, relayer)
}

// OnChanCloseConfirm mocks base method.
func (m *MockIBCModule) OnChanCloseConfirm(ctx types.Context, portID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanCloseConfirm", ctx, portID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnChanCloseConfirm indicates an expected call of OnChanCloseConfirm.
func (mr *MockIBCModuleMockRecorder) OnChanCloseConfirm(ctx, portID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanCloseConfirm", reflect.TypeOf((*MockIBCModule)(nil).OnChanCloseConfirm), ctx, portID, channelID)
}

// OnChanCloseInit mocks base method.
func (m *MockIBCModule) OnChanCloseInit(ctx types.Context, portID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanCloseInit", ctx, portID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnChanCloseInit indicates an expected call of OnChanCloseInit.
func (mr *MockIBCModuleMockRecorder) OnChanCloseInit(ctx, portID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanCloseInit", reflect.TypeOf((*MockIBCModule)(nil).OnChanCloseInit), ctx, portID, channelID)
}

// OnChanOpenAck mocks base method.
func (m *MockIBCModule) OnChanOpenAck(ctx types.Context, portID, channelID, counterpartyChannelID, counterpartyVersion string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanOpenAck", ctx, portID, channelID, counterpartyChannelID, counterpartyVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnChanOpenAck indicates an expected call of OnChanOpenAck.
func (mr *MockIBCModuleMockRecorder) OnChanOpenAck(ctx, portID, channelID, counterpartyChannelID, counterpartyVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanOpenAck", reflect.TypeOf((*MockIBCModule)(nil).OnChanOpenAck), ctx, portID, channelID, counterpartyChannelID, counterpartyVersion)
}

// OnChanOpenConfirm mocks base method.
func (m *MockIBCModule) OnChanOpenConfirm(ctx types.Context, portID, channelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanOpenConfirm", ctx, portID, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnChanOpenConfirm indicates an expected call of OnChanOpenConfirm.
func (mr *MockIBCModuleMockRecorder) OnChanOpenConfirm(ctx, portID, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanOpenConfirm", reflect.TypeOf((*MockIBCModule)(nil).OnChanOpenConfirm), ctx, portID, channelID)
}

// OnChanOpenInit mocks base method.
func (m *MockIBCModule) OnChanOpenInit(ctx types.Context, order types1.Order, connectionHops []string, portID, channelID string, channelCap *types0.Capability, counterparty types1.Counterparty, version string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanOpenInit", ctx, order, connectionHops, portID, channelID, channelCap, counterparty, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnChanOpenInit indicates an expected call of OnChanOpenInit.
func (mr *MockIBCModuleMockRecorder) OnChanOpenInit(ctx, order, connectionHops, portID, channelID, channelCap, counterparty, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanOpenInit", reflect.TypeOf((*MockIBCModule)(nil).OnChanOpenInit), ctx, order, connectionHops, portID, channelID, channelCap, counterparty, version)
}

// OnChanOpenTry mocks base method.
func (m *MockIBCModule) OnChanOpenTry(ctx types.Context, order types1.Order, connectionHops []string, portID, channelID string, channelCap *types0.Capability, counterparty types1.Counterparty, counterpartyVersion string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnChanOpenTry", ctx, order, connectionHops, portID, channelID, channelCap, counterparty, counterpartyVersion)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnChanOpenTry indicates an expected call of OnChanOpenTry.
func (mr *MockIBCModuleMockRecorder) OnChanOpenTry(ctx, order, connectionHops, portID, channelID, channelCap, counterparty, counterpartyVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChanOpenTry", reflect.TypeOf((*MockIBCModule)(nil).OnChanOpenTry), ctx, order, connectionHops, portID, channelID, channelCap, counterparty, counterpartyVersion)
}

// OnRecvPacket mocks base method.
func (m *MockIBCModule) OnRecvPacket(ctx types.Context, packet types1.Packet, relayer types.AccAddress) exported.Acknowledgement {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnRecvPacket", ctx, packet, relayer)
	ret0, _ := ret[0].(exported.Acknowledgement)
	return ret0
}

// OnRecvPacket indicates an expected call of OnRecvPacket.
func (mr *MockIBCModuleMockRecorder) OnRecvPacket(ctx, packet, relayer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRecvPacket", reflect.TypeOf((*MockIBCModule)(nil).OnRecvPacket), ctx, packet, relayer)
}

// OnTimeoutPacket mocks base method.
func (m *MockIBCModule) OnTimeoutPacket(ctx types.Context, packet types1.Packet, relayer types.AccAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnTimeoutPacket", ctx, packet, relayer)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnTimeoutPacket indicates an expected call of OnTimeoutPacket.
func (mr *MockIBCModuleMockRecorder) OnTimeoutPacket(ctx, packet, relayer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnTimeoutPacket", reflect.TypeOf((*MockIBCModule)(nil).OnTimeoutPacket), ctx, packet, relayer)
}
