version: '2'
linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standa
  default: standard
  enable:
    - gosec
    - misspell
    - forcetypeassert
    - exhaustive
    - dogsled
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cosmos/,cosmossdk.io)
        - blank
        - dot
        - localmodule
      custom-order: true
      no-inline-comments: true
      no-prefix-comments: true
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    golines:
      max-len: 120
      tab-len: 4
      shorten-comments: true
      chain-split-dots: true
