// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/autocctp/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAddress struct {
	DestinationDomain uint32 `protobuf:"varint,1,opt,name=destination_domain,json=destinationDomain,proto3" json:"destination_domain,omitempty"`
	MintRecipient     string `protobuf:"bytes,2,opt,name=mint_recipient,json=mintRecipient,proto3" json:"mint_recipient,omitempty"`
	FallbackRecipient string `protobuf:"bytes,3,opt,name=fallback_recipient,json=fallbackRecipient,proto3" json:"fallback_recipient,omitempty"`
	DestinationCaller string `protobuf:"bytes,4,opt,name=destination_caller,json=destinationCaller,proto3" json:"destination_caller,omitempty"`
}

func (m *QueryAddress) Reset()         { *m = QueryAddress{} }
func (m *QueryAddress) String() string { return proto.CompactTextString(m) }
func (*QueryAddress) ProtoMessage()    {}
func (*QueryAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_483d98375be4f886, []int{0}
}
func (m *QueryAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddress.Merge(m, src)
}
func (m *QueryAddress) XXX_Size() int {
	return m.Size()
}
func (m *QueryAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddress.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddress proto.InternalMessageInfo

type QueryAddressResponse struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Exists  bool   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (m *QueryAddressResponse) Reset()         { *m = QueryAddressResponse{} }
func (m *QueryAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAddressResponse) ProtoMessage()    {}
func (*QueryAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_483d98375be4f886, []int{1}
}
func (m *QueryAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddressResponse.Merge(m, src)
}
func (m *QueryAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddressResponse proto.InternalMessageInfo

func (m *QueryAddressResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryAddressResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type QueryStats struct {
}

func (m *QueryStats) Reset()         { *m = QueryStats{} }
func (m *QueryStats) String() string { return proto.CompactTextString(m) }
func (*QueryStats) ProtoMessage()    {}
func (*QueryStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_483d98375be4f886, []int{2}
}
func (m *QueryStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStats.Merge(m, src)
}
func (m *QueryStats) XXX_Size() int {
	return m.Size()
}
func (m *QueryStats) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStats.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStats proto.InternalMessageInfo

type QueryStatsResponse struct {
	Stats map[uint32]DomainStats `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *QueryStatsResponse) Reset()         { *m = QueryStatsResponse{} }
func (m *QueryStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStatsResponse) ProtoMessage()    {}
func (*QueryStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_483d98375be4f886, []int{3}
}
func (m *QueryStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsResponse.Merge(m, src)
}
func (m *QueryStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsResponse proto.InternalMessageInfo

func (m *QueryStatsResponse) GetStats() map[uint32]DomainStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type QueryStatsByDestinationDomain struct {
	DestinationDomain uint32 `protobuf:"varint,1,opt,name=destination_domain,json=destinationDomain,proto3" json:"destination_domain,omitempty"`
}

func (m *QueryStatsByDestinationDomain) Reset()         { *m = QueryStatsByDestinationDomain{} }
func (m *QueryStatsByDestinationDomain) String() string { return proto.CompactTextString(m) }
func (*QueryStatsByDestinationDomain) ProtoMessage()    {}
func (*QueryStatsByDestinationDomain) Descriptor() ([]byte, []int) {
	return fileDescriptor_483d98375be4f886, []int{4}
}
func (m *QueryStatsByDestinationDomain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsByDestinationDomain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsByDestinationDomain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsByDestinationDomain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsByDestinationDomain.Merge(m, src)
}
func (m *QueryStatsByDestinationDomain) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsByDestinationDomain) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsByDestinationDomain.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsByDestinationDomain proto.InternalMessageInfo

type QueryStatsByDestinationDomainResponse struct {
	Accounts         uint64 `protobuf:"varint,1,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Transfers        uint64 `protobuf:"varint,2,opt,name=transfers,proto3" json:"transfers,omitempty"`
	TotalTransferred uint64 `protobuf:"varint,3,opt,name=total_transferred,json=totalTransferred,proto3" json:"total_transferred,omitempty"`
}

func (m *QueryStatsByDestinationDomainResponse) Reset()         { *m = QueryStatsByDestinationDomainResponse{} }
func (m *QueryStatsByDestinationDomainResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStatsByDestinationDomainResponse) ProtoMessage()    {}
func (*QueryStatsByDestinationDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_483d98375be4f886, []int{5}
}
func (m *QueryStatsByDestinationDomainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStatsByDestinationDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStatsByDestinationDomainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStatsByDestinationDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStatsByDestinationDomainResponse.Merge(m, src)
}
func (m *QueryStatsByDestinationDomainResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStatsByDestinationDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStatsByDestinationDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStatsByDestinationDomainResponse proto.InternalMessageInfo

func (m *QueryStatsByDestinationDomainResponse) GetAccounts() uint64 {
	if m != nil {
		return m.Accounts
	}
	return 0
}

func (m *QueryStatsByDestinationDomainResponse) GetTransfers() uint64 {
	if m != nil {
		return m.Transfers
	}
	return 0
}

func (m *QueryStatsByDestinationDomainResponse) GetTotalTransferred() uint64 {
	if m != nil {
		return m.TotalTransferred
	}
	return 0
}

type DomainStats struct {
	Accounts         uint64 `protobuf:"varint,1,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Transfers        uint64 `protobuf:"varint,2,opt,name=transfers,proto3" json:"transfers,omitempty"`
	TotalTransferred uint64 `protobuf:"varint,3,opt,name=total_transferred,json=totalTransferred,proto3" json:"total_transferred,omitempty"`
}

func (m *DomainStats) Reset()         { *m = DomainStats{} }
func (m *DomainStats) String() string { return proto.CompactTextString(m) }
func (*DomainStats) ProtoMessage()    {}
func (*DomainStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_483d98375be4f886, []int{6}
}
func (m *DomainStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DomainStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DomainStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DomainStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainStats.Merge(m, src)
}
func (m *DomainStats) XXX_Size() int {
	return m.Size()
}
func (m *DomainStats) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainStats.DiscardUnknown(m)
}

var xxx_messageInfo_DomainStats proto.InternalMessageInfo

func (m *DomainStats) GetAccounts() uint64 {
	if m != nil {
		return m.Accounts
	}
	return 0
}

func (m *DomainStats) GetTransfers() uint64 {
	if m != nil {
		return m.Transfers
	}
	return 0
}

func (m *DomainStats) GetTotalTransferred() uint64 {
	if m != nil {
		return m.TotalTransferred
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryAddress)(nil), "noble.autocctp.v1.QueryAddress")
	proto.RegisterType((*QueryAddressResponse)(nil), "noble.autocctp.v1.QueryAddressResponse")
	proto.RegisterType((*QueryStats)(nil), "noble.autocctp.v1.QueryStats")
	proto.RegisterType((*QueryStatsResponse)(nil), "noble.autocctp.v1.QueryStatsResponse")
	proto.RegisterMapType((map[uint32]DomainStats)(nil), "noble.autocctp.v1.QueryStatsResponse.StatsEntry")
	proto.RegisterType((*QueryStatsByDestinationDomain)(nil), "noble.autocctp.v1.QueryStatsByDestinationDomain")
	proto.RegisterType((*QueryStatsByDestinationDomainResponse)(nil), "noble.autocctp.v1.QueryStatsByDestinationDomainResponse")
	proto.RegisterType((*DomainStats)(nil), "noble.autocctp.v1.DomainStats")
}

func init() { proto.RegisterFile("noble/autocctp/v1/query.proto", fileDescriptor_483d98375be4f886) }

var fileDescriptor_483d98375be4f886 = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x3f, 0x6f, 0x13, 0x4f,
	0x10, 0xf5, 0x3a, 0x76, 0xfe, 0x6c, 0x92, 0x9f, 0xe2, 0x55, 0x8a, 0xfb, 0x1d, 0xf8, 0x1c, 0x0e,
	0x59, 0x44, 0x88, 0xf8, 0x88, 0xa1, 0x88, 0xd2, 0x61, 0x42, 0x47, 0xc3, 0x05, 0xa4, 0x28, 0x8d,
	0xb5, 0x39, 0x6f, 0xac, 0x23, 0xe7, 0x5d, 0x73, 0xbb, 0xb6, 0xb0, 0x22, 0x37, 0x54, 0xa1, 0x43,
	0xe2, 0x0b, 0x44, 0xa2, 0x80, 0x92, 0x82, 0x92, 0x0a, 0x09, 0x29, 0x05, 0x45, 0x80, 0x86, 0x0a,
	0xa1, 0x04, 0x09, 0x0a, 0x3e, 0x04, 0xba, 0xdd, 0xfb, 0x17, 0xec, 0x18, 0x52, 0x20, 0x9a, 0xe8,
	0x76, 0xde, 0x9b, 0x99, 0xb7, 0x33, 0xfb, 0x62, 0x58, 0xa4, 0x6c, 0xcb, 0x23, 0x16, 0xee, 0x08,
	0xe6, 0x38, 0xa2, 0x6d, 0x75, 0x97, 0xad, 0x07, 0x1d, 0xe2, 0xf7, 0x2a, 0x6d, 0x9f, 0x09, 0x86,
	0x0a, 0x12, 0xae, 0x44, 0x70, 0xa5, 0xbb, 0xac, 0x17, 0x70, 0xcb, 0xa5, 0xcc, 0x92, 0x7f, 0x15,
	0x4b, 0x3f, 0xe7, 0x30, 0xde, 0x62, 0x5c, 0x65, 0xfe, 0x52, 0x42, 0xff, 0x5f, 0x81, 0x75, 0x79,
	0xb2, 0xd4, 0x21, 0x84, 0xe6, 0x9b, 0xac, 0xc9, 0x54, 0x3c, 0xf8, 0x0a, 0xa3, 0xe7, 0x9b, 0x8c,
	0x35, 0x03, 0x4d, 0x6d, 0xd7, 0xc2, 0x94, 0x32, 0x81, 0x85, 0xcb, 0x68, 0x98, 0x63, 0xbe, 0x03,
	0x70, 0xe6, 0x4e, 0x50, 0xfe, 0x46, 0xa3, 0xe1, 0x13, 0xce, 0xd1, 0x12, 0x44, 0x0d, 0xc2, 0x85,
	0x4b, 0x25, 0xad, 0xde, 0x60, 0x2d, 0xec, 0x52, 0x0d, 0x2c, 0x80, 0xc5, 0x59, 0xbb, 0x90, 0x42,
	0xd6, 0x24, 0x80, 0xca, 0xf0, 0xbf, 0x96, 0x4b, 0x45, 0xdd, 0x27, 0x8e, 0xdb, 0x76, 0x09, 0x15,
	0x5a, 0x76, 0x01, 0x2c, 0x4e, 0xd9, 0xb3, 0x41, 0xd4, 0x8e, 0x82, 0x41, 0xd5, 0x6d, 0xec, 0x79,
	0x5b, 0xd8, 0xd9, 0x49, 0x51, 0xc7, 0x24, 0xb5, 0x10, 0x21, 0x27, 0xe8, 0x69, 0x11, 0x0e, 0xf6,
	0x3c, 0xe2, 0x6b, 0x39, 0x45, 0x4f, 0x21, 0x37, 0x25, 0xb0, 0x3a, 0xb9, 0xb7, 0x5f, 0xca, 0x7c,
	0xdf, 0x2f, 0x65, 0x4c, 0x17, 0xce, 0xa7, 0x6f, 0x63, 0x13, 0xde, 0x66, 0x94, 0x13, 0x54, 0x85,
	0x13, 0x58, 0x85, 0xe4, 0x55, 0xa6, 0x6a, 0xda, 0x87, 0x57, 0x4b, 0xf3, 0xe1, 0xf4, 0x42, 0xf2,
	0xba, 0xf0, 0x5d, 0xda, 0xb4, 0x23, 0x22, 0x2a, 0xc2, 0x71, 0xf2, 0xd0, 0xe5, 0x82, 0xcb, 0x2b,
	0x4d, 0xd6, 0xf2, 0x2f, 0xbe, 0xbd, 0xbc, 0x0c, 0xec, 0x30, 0x68, 0xce, 0x40, 0x28, 0x5b, 0xad,
	0x0b, 0x2c, 0xb8, 0xf9, 0x1a, 0x40, 0x94, 0x1c, 0xe3, 0xbe, 0xb7, 0x61, 0x9e, 0x07, 0x01, 0x0d,
	0x2c, 0x8c, 0x2d, 0x4e, 0x57, 0xaf, 0x56, 0x06, 0x1e, 0x40, 0x65, 0x30, 0xab, 0x22, 0x4f, 0xb7,
	0xa8, 0xf0, 0x7b, 0xb5, 0xdc, 0xc1, 0xe7, 0x52, 0xc6, 0x56, 0x45, 0xf4, 0x0d, 0x08, 0x13, 0x08,
	0xcd, 0xc1, 0xb1, 0x1d, 0xd2, 0x0b, 0x57, 0x13, 0x7c, 0xa2, 0xeb, 0x30, 0xdf, 0xc5, 0x5e, 0x87,
	0x48, 0xc1, 0xd3, 0x55, 0x63, 0x48, 0x37, 0xb5, 0x36, 0xd5, 0x4e, 0x91, 0x57, 0xb3, 0x2b, 0xc0,
	0xdc, 0x80, 0xc5, 0x44, 0x47, 0xad, 0xb7, 0x36, 0xb0, 0xe7, 0xb3, 0x3d, 0x8b, 0xd4, 0x46, 0x9e,
	0x01, 0x58, 0x1e, 0x59, 0x3a, 0x9e, 0xd5, 0x05, 0x38, 0x89, 0x1d, 0x87, 0x75, 0xa8, 0x50, 0x4b,
	0xca, 0x45, 0x13, 0x8f, 0xc3, 0xe8, 0x22, 0x9c, 0x12, 0x3e, 0xa6, 0x7c, 0x9b, 0xf8, 0x6a, 0x2b,
	0x31, 0x27, 0x89, 0xa3, 0x2a, 0x2c, 0x08, 0x26, 0xb0, 0x57, 0x8f, 0x42, 0x3e, 0x69, 0xc8, 0xa7,
	0x16, 0x93, 0xe7, 0x24, 0x7e, 0x37, 0x81, 0xcd, 0xc7, 0x00, 0x4e, 0xa7, 0x46, 0xf3, 0x2f, 0xb5,
	0x54, 0x7f, 0xe4, 0x60, 0x5e, 0x4e, 0x0c, 0x3d, 0xcf, 0xc2, 0x89, 0xc8, 0x97, 0xa5, 0xd3, 0x9e,
	0x4e, 0x48, 0xd0, 0x2f, 0xfd, 0x86, 0x10, 0xcd, 0xd9, 0x7c, 0x0f, 0xf6, 0x82, 0xce, 0x8f, 0x3e,
	0x7e, 0x7d, 0x9a, 0x7d, 0x0b, 0x36, 0x3d, 0x74, 0xdf, 0x1a, 0xfc, 0xaf, 0x15, 0x9a, 0xc0, 0xda,
	0x1d, 0xdc, 0x7a, 0xdf, 0xda, 0x3d, 0x69, 0xf9, 0xbe, 0xb5, 0x3b, 0x68, 0xee, 0xfe, 0xc9, 0x54,
	0x65, 0xe1, 0x3e, 0xba, 0xf7, 0x57, 0x7a, 0x21, 0x01, 0xf3, 0x6a, 0x71, 0xc5, 0x91, 0x0e, 0xd3,
	0xcb, 0x7f, 0x64, 0x40, 0xb3, 0x9c, 0x4c, 0x48, 0x47, 0xda, 0x10, 0xc9, 0xd2, 0x8f, 0xe8, 0x0d,
	0x80, 0xda, 0xa9, 0x8e, 0x19, 0xed, 0xf5, 0x21, 0x19, 0xfa, 0xca, 0x59, 0x33, 0x62, 0xbd, 0xab,
	0x89, 0x5e, 0x0b, 0x2d, 0x9d, 0xa6, 0x77, 0xe8, 0x80, 0x6b, 0x57, 0x0e, 0x8e, 0x0c, 0x70, 0x78,
	0x64, 0x80, 0x2f, 0x47, 0x06, 0x78, 0x72, 0x6c, 0x64, 0x0e, 0x8f, 0x8d, 0xcc, 0xa7, 0x63, 0x23,
	0xb3, 0x89, 0x62, 0x21, 0x0d, 0xd2, 0xb5, 0x44, 0xaf, 0x4d, 0xf8, 0xd6, 0xb8, 0xfc, 0xd9, 0xb8,
	0xf6, 0x33, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xff, 0x95, 0xea, 0xe9, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Address(ctx context.Context, in *QueryAddress, opts ...grpc.CallOption) (*QueryAddressResponse, error)
	Stats(ctx context.Context, in *QueryStats, opts ...grpc.CallOption) (*QueryStatsResponse, error)
	StatsByDestinationDomain(ctx context.Context, in *QueryStatsByDestinationDomain, opts ...grpc.CallOption) (*QueryStatsByDestinationDomainResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Address(ctx context.Context, in *QueryAddress, opts ...grpc.CallOption) (*QueryAddressResponse, error) {
	out := new(QueryAddressResponse)
	err := c.cc.Invoke(ctx, "/noble.autocctp.v1.Query/Address", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Stats(ctx context.Context, in *QueryStats, opts ...grpc.CallOption) (*QueryStatsResponse, error) {
	out := new(QueryStatsResponse)
	err := c.cc.Invoke(ctx, "/noble.autocctp.v1.Query/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StatsByDestinationDomain(ctx context.Context, in *QueryStatsByDestinationDomain, opts ...grpc.CallOption) (*QueryStatsByDestinationDomainResponse, error) {
	out := new(QueryStatsByDestinationDomainResponse)
	err := c.cc.Invoke(ctx, "/noble.autocctp.v1.Query/StatsByDestinationDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Address(context.Context, *QueryAddress) (*QueryAddressResponse, error)
	Stats(context.Context, *QueryStats) (*QueryStatsResponse, error)
	StatsByDestinationDomain(context.Context, *QueryStatsByDestinationDomain) (*QueryStatsByDestinationDomainResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Address(ctx context.Context, req *QueryAddress) (*QueryAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Address not implemented")
}
func (*UnimplementedQueryServer) Stats(ctx context.Context, req *QueryStats) (*QueryStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (*UnimplementedQueryServer) StatsByDestinationDomain(ctx context.Context, req *QueryStatsByDestinationDomain) (*QueryStatsByDestinationDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatsByDestinationDomain not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Address_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Address(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.autocctp.v1.Query/Address",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Address(ctx, req.(*QueryAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.autocctp.v1.Query/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Stats(ctx, req.(*QueryStats))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StatsByDestinationDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStatsByDestinationDomain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StatsByDestinationDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.autocctp.v1.Query/StatsByDestinationDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StatsByDestinationDomain(ctx, req.(*QueryStatsByDestinationDomain))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noble.autocctp.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Address",
			Handler:    _Query_Address_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Query_Stats_Handler,
		},
		{
			MethodName: "StatsByDestinationDomain",
			Handler:    _Query_StatsByDestinationDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noble/autocctp/v1/query.proto",
}

func (m *QueryAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DestinationCaller) > 0 {
		i -= len(m.DestinationCaller)
		copy(dAtA[i:], m.DestinationCaller)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DestinationCaller)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FallbackRecipient) > 0 {
		i -= len(m.FallbackRecipient)
		copy(dAtA[i:], m.FallbackRecipient)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FallbackRecipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MintRecipient) > 0 {
		i -= len(m.MintRecipient)
		copy(dAtA[i:], m.MintRecipient)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MintRecipient)))
		i--
		dAtA[i] = 0x12
	}
	if m.DestinationDomain != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DestinationDomain))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exists {
		i--
		if m.Exists {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Stats) > 0 {
		for k := range m.Stats {
			v := m.Stats[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i = encodeVarintQuery(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintQuery(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryStatsByDestinationDomain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsByDestinationDomain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsByDestinationDomain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DestinationDomain != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DestinationDomain))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryStatsByDestinationDomainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStatsByDestinationDomainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStatsByDestinationDomainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalTransferred != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalTransferred))
		i--
		dAtA[i] = 0x18
	}
	if m.Transfers != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Transfers))
		i--
		dAtA[i] = 0x10
	}
	if m.Accounts != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Accounts))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DomainStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DomainStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DomainStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalTransferred != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalTransferred))
		i--
		dAtA[i] = 0x18
	}
	if m.Transfers != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Transfers))
		i--
		dAtA[i] = 0x10
	}
	if m.Accounts != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Accounts))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DestinationDomain != 0 {
		n += 1 + sovQuery(uint64(m.DestinationDomain))
	}
	l = len(m.MintRecipient)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.FallbackRecipient)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.DestinationCaller)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Exists {
		n += 2
	}
	return n
}

func (m *QueryStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Stats) > 0 {
		for k, v := range m.Stats {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + sovQuery(uint64(k)) + 1 + l + sovQuery(uint64(l))
			n += mapEntrySize + 1 + sovQuery(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *QueryStatsByDestinationDomain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DestinationDomain != 0 {
		n += 1 + sovQuery(uint64(m.DestinationDomain))
	}
	return n
}

func (m *QueryStatsByDestinationDomainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Accounts != 0 {
		n += 1 + sovQuery(uint64(m.Accounts))
	}
	if m.Transfers != 0 {
		n += 1 + sovQuery(uint64(m.Transfers))
	}
	if m.TotalTransferred != 0 {
		n += 1 + sovQuery(uint64(m.TotalTransferred))
	}
	return n
}

func (m *DomainStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Accounts != 0 {
		n += 1 + sovQuery(uint64(m.Accounts))
	}
	if m.Transfers != 0 {
		n += 1 + sovQuery(uint64(m.Transfers))
	}
	if m.TotalTransferred != 0 {
		n += 1 + sovQuery(uint64(m.TotalTransferred))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationDomain", wireType)
			}
			m.DestinationDomain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestinationDomain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FallbackRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FallbackRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationCaller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationCaller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exists", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exists = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stats == nil {
				m.Stats = make(map[uint32]DomainStats)
			}
			var mapkey uint32
			mapvalue := &DomainStats{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthQuery
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthQuery
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &DomainStats{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipQuery(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthQuery
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Stats[mapkey] = *mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsByDestinationDomain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsByDestinationDomain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsByDestinationDomain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationDomain", wireType)
			}
			m.DestinationDomain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestinationDomain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStatsByDestinationDomainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStatsByDestinationDomainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStatsByDestinationDomainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accounts", wireType)
			}
			m.Accounts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Accounts |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transfers", wireType)
			}
			m.Transfers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Transfers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTransferred", wireType)
			}
			m.TotalTransferred = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalTransferred |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DomainStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DomainStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DomainStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accounts", wireType)
			}
			m.Accounts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Accounts |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transfers", wireType)
			}
			m.Transfers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Transfers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTransferred", wireType)
			}
			m.TotalTransferred = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalTransferred |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
