name: Lint

on:
  pull_request:

jobs:
  lint:
    name: 🧹
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
        